"""Shared constants for the Stage 1 implementation."""

TEMPORAL_PHRASES = (
    "this year",
    "last year",
    "next year",
    "recent",
    "recently",
    "current",
    "currently",
    "latest",
    "newest",
    "former",
    "previous",
    "as of",
)

MONTH_NAMES = (
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
)

REJECTION_REASONS = {
    "subject_label_contains_temporal_expression",
    "subject_label_contains_year",
    "answer_not_time_invariant",
    "future_dated_or_unsettled_fact",
    "mutable_relationship_or_status",
    "mutable_affiliation_or_office",
    "cumulative_statistic",
    "answer_not_unique",
    "no_english_label",
    "no_answer_label",
    "same_label_competitor_requires_temporal_disambiguation",
    "no_non_temporal_signature",
    "descriptor_leaks_answer",
    "canonical_question_failed_validation",
    "rewrite_contains_year",
    "rewrite_contains_temporal_expression",
    "rewrite_lost_required_anchor",
    "rewrite_leaks_answer",
    "duplicate_question",
    "duplicate_subject_resource",
    "quota_exceeded",
    "reasoning_path_not_connected",
    "shortcut_answerable_without_all_hops",
    "bridge_entity_leaks_answer",
    "provenance_incomplete",
    "ordinal_derivation_not_safe",
}
